server {
    listen 80;
    server_name headscale.dash.ps;
    location / {
        proxy_pass http://100.105.90.110:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name headscaleui.dash.ps;
    location / { proxy_pass http://100.105.90.110:8081; }
}

server {
    listen 80;
    server_name headscaleproxy.dash.ps;
    location / { proxy_pass http://100.105.90.110:8082; }
}

server {
    listen 80;
    server_name uptime.dash.ps;
    location / { proxy_pass http://100.105.90.110:3001; }
}

server {
    listen 80;
    server_name grafana.dash.ps;
    location / { proxy_pass http://100.105.90.110:3000; }
}

server {
    listen 80;
    server_name prometheus.dash.ps;
    location / { proxy_pass http://100.105.90.110:9091; }
}
